### ISSUE TITLE
Exec filter date command not working correctly

### ISSUE THREAD

**Issue by rsingh2411** [logstash-plugins/logstash-output-exec#13]
The following config was working in 2.3.2, we upgraded this to 5.3.2  and then 5.4.0 both had similar error.

- Version: 3.1.0
- Operating System: linux
- Config File 
`input { stdin {
}
heartbeat {
     interval => 10
     type => "heartbeat"
}
}
output {
    if [type] == "heartbeat" {
        exec {
            codec => "json"
           command => "date +%s > /tmp/heartbeat"
        }
    }
    stdout { codec => rubydebug }
}
`

- Steps to Reproduce: 
1. use above config and run logstash with any log file in debug mode
Following errors are recieved
`  debugging command {:stdout=>"", :stderr=>"date: extra operand ‘>’\nTry 'date --help' for more information."}`
further debugging error message
`debugging command {:stdout=>"", :stderr=>"BusyBox v1.24.2 (2016-06-22 17:51:28 GMT) multi-call binary.\n\nUsage: date [OPTIONS] [+FMT] [TIME]\n\nDisplay time (using +FMT), or set time\n\n\t[-s,--set] TIME\tSet time to TIME\n\t-u,--utc\tWork in UTC (don't convert to local time)\n\t-R,--rfc-2822\tOutput RFC-2822 compliant date string\n\t-I[SPEC]\tOutput ISO-8601 compliant date string\n\t\t\tSPEC='date' (default) for date only,\n\t\t\t'hours', 'minutes', or 'seconds' for date and\n\t\t\ttime to the indicated precision\n\t-r,--reference FILE\tDisplay last modification time of FILE\n\t-d,--date TIME\tDisplay TIME, not 'now'\n\t-D FMT\t\tUse FMT for -d TIME conversion\n\nRecognized TIME formats:\n\thh:mm[:ss]\n\t[YYYY.]MM.DD-hh:mm[:ss]\n\tYYYY-MM-DD hh:mm[:ss]\n\t[[[[[YY]YY]MM]DD]hh]mm[.ss]\n\t'date TIME' form accepts MMDDhhmm[[YY]YY][.ss] instead"}`

Workaround instead of running command, using running a shell script containing the command

**Comment by magnusbaeck** [comment]
@ph, in #7 you replaced the use of Kernel.system with Open3.popen3. Was it intentional to no longer pass the command to a shell? As this issue exhibits that change its behavior can be material for some use cases. Even if the change was intentional it should've warranted a major version step to indicate the backwards compatibility break.

**Comment by magnusbaeck** [comment]
@ph, could you please have a look at the question I posted in the previous comment?

> Workaround instead of running command, using running a shell script containing the command

You can also configure Logstash to run `sh -c "date +%s > /tmp/heartbeat"`.

**Comment by magnusbaeck** [comment]
I can't reproduce this in Logstash 6.3.2. I suspect this is because Open3::popen3 in JRuby pre-9k used in earlier Logstash releases didn't pass the string to a shell but the JRuby used in recent Logstash releases does.
