### ISSUE TITLE
Double quote missing on command line

### ISSUE THREAD

**Issue by wadinj** [logstash-plugins/logstash-output-exec#17]
Please post all product and debugging questions on our [forum](https://discuss.elastic.co/c/logstash). Your questions will reach our wider community members there, and if we confirm that there is a bug, then we can open a new issue here.

For all general issues, please provide the following details for fast resolution:

- Version: Logstash 6.4.2 / logstash-output-exec (3.1.4)
- Operating System: Windows Version 10.0.16299 Build 16299
- Config File (if you have sensitive info, please remove it):
`exec {
      command => "curl -d \" %{process_metrics} \" -X POST https://server:port/PublishProcessMetrics  
}`
Process_metrics variable contains a JSON text well formatted example : 
`"{ \"EventType\": \"Client/Server Call\", \"TraceId\": \"123AB21\", \"StartDate\": \"2011-02-07 23:31:41 UTC\", \"Pid\": \"132442\" }"`

When exec output launch curl command, it remove the surrounding \" and the double quote of the JSON variable.

**Comment by magnusbaeck** [comment]
I don't think that's what the `process_metrics` field _really_ contains. Please use a `stdout { codec => rubydebug }` output to dump a raw example event.

Why aren't you using the http output for this? I think your question stems from a misunderstanding, but even if we clear that misunderstanding the approach is fundamentally flawed and won't work reliably.

As the first paragraph of your issue (from the issue template) indicates this is something that would've been a better fit for https://discuss.elastic.co/c/logstash.

**Comment by wadinj** [comment]
This is already the copy of the output of the `stdout { codec => rebydebug }`.
I use the curl instead of the http output plugin because the http plugin doesn't support the ntml authentification. Maybe this is a poor workaround and I'll figure out a reliable solution.
Anyway, the double quote are missing from the json message.

**Comment by magnusbaeck** [comment]
Okay. So what happens here is that the contents of the `process_metrics` field,

    { "EventType": "Client/Server Call", "TraceId": "123AB21", "StartDate": "2011-02-07 23:31:41 UTC", "Pid": "132442" }

is interpolated into the command string,

    curl -d " %{process_metrics} " -X POST https://server:port/PublishProcessMetrics

producing this string that's passed to [Ruby's Open3::popen3 method](https://ruby-doc.org/stdlib-1.9.3/libdoc/open3/rdoc/Open3.html#method-c-popen3):

    curl -d " { "EventType": "Client/Server Call", "TraceId": "123AB21", "StartDate": "2011-02-07 23:31:41 UTC", "Pid": "132442" } " -X POST https://server:port/PublishProcessMetrics

When passed to a shell or a parser that pretends to be a shell there won't be any double quotes left. You'll have to escape the double quotes in the JSON string (uncertain if that would be `\"` or `""` given that this is on Windows).

So, the absence of double quotes is expected in this case.
